### ISSUE TITLE
Is it possible to produce maelstrom visualisations with results from a jepsen test?

### ISSUE THREAD

**Issue by zackteo** [jepsen-io/maelstrom#13]
Hi Kyle, I managed to use Jepsen to do some simple tests on my distributed system.

And I was wondering if it is possible to use maelstrom on my Jepsen test results to produce some of visualisations here https://github.com/jepsen-io/maelstrom/blob/main/doc/results.md#common-files ?

**Comment by zackteo** [comment]
Whoops I forgot that the inclusion of `checker` will generate `latency-raw.png` `latency-quantiles.png` and `timeline.html`. 

I guess `messages.svg`, `messages.svg` and `log/n*.log` are only possible if maelstrom is used? 🤔

**Comment by aphyr** [comment]
Almost all of Maelstrom is stock Jepsen, so yeah, almost all visualizations are already available. The only one which isn't is `messages.svg`, which Jepsen can't generate without deep understanding of the wire protocols for the database being tested. `jepsen.db/tcpdump` can record message flows for you, and you can analyze them in wireshark, but that won't really get you to Lamport diagrams either. You'd need to write some kind of custom software for that, I think.
