### ISSUE TITLE
Missing v0.2.1 artifact?

### ISSUE THREAD

**Issue by danhhz** [jepsen-io/maelstrom#25]
Hey! Sorry if I'm blind, but it looks like v0.2.1 doesn't have a pre-built jar, but the other versions do. 

0.2.1: https://github.com/jepsen-io/maelstrom/releases/tag/0.2.1 (no maelstrom.tar.bz2, just the sources)
0.2.0: https://github.com/jepsen-io/maelstrom/releases/tag/0.2.0 (has a jar in maelstrom.tar.bz2)

Any chance you'd be willing to toss one up? I don't have a closure dev environment set up. Thanks!

**Comment by aphyr** [comment]
Oh jeez, yeah, this is my bad. I'm absolutely swamped for the next uhhhh... 6 days, but after?

**Comment by danhhz** [comment]
That would be lovely. No hurry!

**Comment by danhhz** [comment]
Thanks, Kyle!
