### ISSUE TITLE
Namesis partition issue?

### ISSUE THREAD

**Issue by teivah** [jepsen-io/maelstrom#44]
Hello,

First of thanks for all your work.

I'm working on Gossip Glomers, challenge 3c. The main change is that we add `--nemesis partition` to test network partitions. When I test it against my [solution](https://github.com/teivah/gossip-glomers/blob/e694ba88800a094667e5c8d0248d151eea6dc7e3/challenge-3c-broadcast/main.go#L65) for 3b, which *doesn't* handle network partitions, I'm getting an `Everything looks good!`.

That led me to think that perhaps, the `--nemesis partition` wasn't working correctly as, again, the test should have failed because my solution doesn't handle network partitions.

**Comment by avinassh** [comment]
I can confirm this is happening for me also. The same code which I have for 3b also passes 3c. Then I ran the maelstorm multiple times, it did fail. So I am guessing that there is always some chance that network partition might not cause any issue for a brief time during the test, so running the suite multiple times may be a better idea. 

OR there could be a bug
