### ISSUE TITLE
Error: Unable to access jarfile lib/maelstrom.jar

### ISSUE THREAD

**Issue by Ederene20** [jepsen-io/maelstrom#48]
Hello, I hope you are doing well. I just started the Gossip Glomers Echo Challenge, but I am running into an error. 
I have installed Maelstrom and its prerequisites but when I hit the command `./maelstrom test -w echo --bin ~/go/bin/maelstrom-echo --node-count 1 --time-limit 10`, I get the following error `Error: Unable to access jarfile lib/maelstrom.jar`

Screenshot: 
![Screenshot from 2023-02-28 13-35-01](https://user-images.githubusercontent.com/71341317/221856560-9f9d29b0-a75e-4aaf-9ea8-cdb23d85ba31.png)

**Comment by aphyr** [comment]
It looks like you downloaded the source, not the release tarball. You can build the project from source too, if you like: it's a standard lein project.On Feb 28, 2023 07:47, "Ruben Atinho H." ***@***.***> wrote:
Hello, I hope you are doing well. I just started the Gossip Glomers Echo Challenge, but I am running into an error.
I have installed Maelstrom and its prerequisites but when I hit the command ./maelstrom test -w echo --bin ~/go/bin/maelstrom-echo --node-count 1 --time-limit 10, I get the following error Error: Unable to access jarfile lib/maelstrom.jar
Screenshot:

**Comment by Ederene20** [comment]
> It looks like you downloaded the source, not the release tarball. You can build the project from source too, if you like: it's a standard lein project.On Feb 28, 2023 07:47, "Ruben Atinho H." ***@***.***> wrote: Hello, I hope you are doing well. I just started the Gossip Glomers Echo Challenge, but I am running into an error. I have installed Maelstrom and its prerequisites but when I hit the command ./maelstrom test -w echo --bin ~/go/bin/maelstrom-echo --node-count 1 --time-limit 10, I get the following error Error: Unable to access jarfile lib/maelstrom.jar Screenshot: —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you very much @aphyr. Everything looks good!
