### ISSUE TITLE
Python client library

### ISSUE THREAD

**Issue by ekzhang** [jepsen-io/maelstrom#66]
Hi there! Thanks so much for making Maelstrom. I just ran a small workshop at a [systems reading group](https://notes.ekzhang.com/events/hsrg) that I organize at Harvard, and we all worked on the Gossip Glomers challenges together on a shared remote computer. It was a lot of fun :)

![image](https://user-images.githubusercontent.com/7550632/232255172-c1f38636-4ff3-457d-8dfc-c576253a9f63.png)

I wrote a Python client library for Maelstrom (via `asyncio`) for the purposes of the workshop, since I did a quick poll, and most of the members of our reading group didn't know Go or JavaScript but were still interested in learning about distributed systems. I thought it might be helpful for others who are more familiar with Python as well. Would you be open to a pull request where I add this library to the `demo/` folder for others to use?

https://gist.github.com/ekzhang/65310f0260c03d4ec340e0daf0ccb9d5#file-_maelstrom-py

**Comment by aphyr** [comment]
Sure, go for it!
